const ProductServices = require('../services/product.services');
const { validateProductData } = require('../utils/validator');


exports.handleCreate = async (req, res) => {

    try {


    let { valid, errors } = validateProductData(req.body);
        if (!valid) return res.status(400).json({ message: 'Something went wrong!', errors })

    let resp = await ProductServices.createRecord(req.body)
        return res.status(200).json({ message: "Created Successfully", data: resp });
    } catch (err) {
        res.status(400).json({ message: "Something went wronged!", errors: err });
    }

};



exports.handleGetById = async (req, res) => {
    let { id } = req.params;
    resp = await ProductServices.getById(id);
    res.status(200).json({ message: "Fetch Success", data: resp });
};

exports.handleGetAll = async (req, res) => {
    let resp = await ProductServices.getAll();
    res.status(200).json({ message: "Fetch Successfully", data: resp });
};

exports.handleDeleteById = async (req, res) => {
    let { id } = req.params;
    let resp = await ProductServices.deleteRecord(id)


    res.status(200).json({ message: "Deleted Successfully", data: resp });
};


exports.handleUpdateById = async (req, res) => {
    let { id } = req.params;

    try {
        let resp = await ProductServices.updateRecord(id, req.body);
        res.status(200).json({ message: "Updated Successfully", data: resp });
    } catch (err) {
        console.log(err)
        res.status(400).json({ message: 'Something went wrong!' })
    }
}

